// <auto-generated />
using Aquirrel.EntityFramework.Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Aquirrel.EntityFramework.Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20170725064822_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview2-25794")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aquirrel.EntityFramework.Test.AutoEntryTable", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastModfiyDate");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("name")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Table_attr_name");
                });

            modelBuilder.Entity("Aquirrel.EntityFramework.Test.ModelA", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastModfiyDate");

                    b.Property<string>("StringDefault")
                        .HasMaxLength(32);

                    b.Property<string>("StringMax")
                        .HasMaxLength(32);

                    b.Property<string>("StringSetLength")
                        .HasMaxLength(640);

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<decimal>("decimalDefault");

                    b.Property<decimal>("decimalSetSacle")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("intDefault");

                    b.HasKey("Id");

                    b.ToTable("ModelASet");
                });
#pragma warning restore 612, 618
        }
    }
}
