// <auto-generated />
using Aquirrel.EntityFramework.Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Aquirrel.EntityFramework.Test.Migrations
{
    [DbContext(typeof(TestDbContext))]
    partial class TestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-preview2-25794")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Aquirrel.EntityFramework.Test.ModelA", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<string>("AId")
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastModfiyDate");

                    b.Property<string>("Name")
                        .HasAnnotation("IsMaxLength", true);

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.HasIndex("AId");

                    b.ToTable("ModelA");
                });

            modelBuilder.Entity("Aquirrel.EntityFramework.Test.ModelB", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<string>("AId")
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Desc")
                        .HasMaxLength(22);

                    b.Property<DateTime>("LastModfiyDate");

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("ModelB");
                });

            modelBuilder.Entity("Aquirrel.EntityFramework.Test.ModelC", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("Date");

                    b.Property<string>("HH")
                        .HasMaxLength(32);

                    b.Property<DateTime>("LastModfiyDate");

                    b.Property<string>("MaxLen")
                        .HasMaxLength(32);

                    b.Property<int>("Version");

                    b.HasKey("Id");

                    b.ToTable("ModelC");
                });

            modelBuilder.Entity("Aquirrel.EntityFramework.Test.ModelA", b =>
                {
                    b.HasOne("Aquirrel.EntityFramework.Test.ModelB")
                        .WithMany("ModelA")
                        .HasForeignKey("AId");
                });
#pragma warning restore 612, 618
        }
    }
}
