// <auto-generated />
using Aquirrel.EntityFramework.Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Aquirrel.EntityFramework.Test.Migrations.rv
{
    [DbContext(typeof(RVDbContext))]
    [Migration("20170919101259_init001")]
    partial class init001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Aquirrel.EntityFramework.Test.ModelA", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastModfiyDate");

                    b.Property<int>("RowVersion");

                    b.Property<string>("StringDefault")
                        .HasMaxLength(32);

                    b.Property<string>("StringMax");

                    b.Property<string>("StringMaxLenAttr")
                        .HasMaxLength(999);

                    b.Property<string>("StringSetLength")
                        .HasMaxLength(640);

                    b.Property<decimal>("decimalDefault");

                    b.Property<decimal>("decimalSetSacle")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("intDefault");

                    b.HasKey("Id");

                    b.ToTable("ModelASet");
                });

            modelBuilder.Entity("Aquirrel.EntityFramework.Test.ShardTable", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("DecimalSacle")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DefaultName")
                        .HasMaxLength(32);

                    b.Property<DateTime>("LastModfiyDate");

                    b.Property<string>("MaxName")
                        .HasMaxLength(32);

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken();

                    b.HasKey("Id");

                    b.ToTable("ShardTable");
                });
#pragma warning restore 612, 618
        }
    }
}
