// <auto-generated />
using System;
using Aquirrel.EntityFramework.Test;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aquirrel.EntityFramework.Test.Migrations.rv
{
    [DbContext(typeof(RVDbContext))]
    [Migration("20181031095646_init001")]
    partial class init001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("Aquirrel.EntityFramework.Test.ModelA", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastModfiyDate");

                    b.Property<int>("RowVersion");

                    b.Property<string>("StringDefault");

                    b.Property<string>("StringMax");

                    b.Property<string>("StringMaxLenAttr")
                        .HasMaxLength(999);

                    b.Property<string>("StringSetLength")
                        .HasMaxLength(640);

                    b.Property<decimal>("decimalDefault");

                    b.Property<decimal>("decimalSetSacle");

                    b.Property<int>("intDefault");

                    b.HasKey("Id");

                    b.ToTable("ModelASet");
                });
#pragma warning restore 612, 618
        }
    }
}
